version: "3"

tasks:
  build:
    dir: swa/
    cmds:
      - flutter build web

  run:
    dir: swa/
    cmds:
      - flutter run -d chrome

  swa:
    deps: [build]
    cmds:
      - |
        swa start \
          --app-location ./swa/ \
          --api-location ./api/ \
          --output-location build/web/
