version: "3"

tasks:
  build:
    dir: swa/
    cmds:
      - npm run build

  run:
    dir: swa/
    cmds:
      - npm run dev

  swa:
    cmds:
      - |
        swa start http://localhost:4321 \
          --run 'npm run dev' \
          --app-location ./swa/ \
          --api-location ./api/ \
          --output-location dist/
