version: "3"

tasks:
  npm-install:
    cmds:
      - cd api && npm install
      - cd swa && npm install

  build:
    cmds:
      - swa build --api-location api/ --app-location swa/ --auto

  run:
    deps:
      - build
    cmds:
      - |
        PATH="/opt/homebrew/opt/node@18/bin:$PATH"
        swa start \
          --app-devserver-url http://localhost:4321 \
          --run 'npm run dev' \
          --app-location ./swa/ \
          --api-location ./api/ \
          --output-location dist/
